### ISSUE TITLE
Organizar repo

### ISSUE THREAD

**Issue by felipessalvatore** [MLIME/amazonproject#1]
Oi pessoal, eu tenho algumas sugestoes:

1.  Acabei de criar uma branch ( - tf - nao sou bom com nomes). Acho que seria muito legal se concordássemos **todos** em não submeter commits diretos, mas sim usando pull requests para darmos a chance de todos opinarem... o que acham?

2 - @mespadoto ha duas coisas em como voce organizou o repositiorio que queria discutir. i) Sempre acho legal nao colocar arquivos que nao sao codigo no repositorio (tirando certas imagens pontuais, ou um pdf, mas bem pouco). Geralmente o que eu faco eu crio um script em bash para pegar os arquivos em algum lugar. Se voce olhar no meu branch tf eu fiz isso com o arquivo "train.csv". A questao que surge a seguir eh onde deixar esses arquivos. Como para baixar direto do kaggle precisa fazer um login, eu estava pensando em criar uma conta do grupo no dropbox  para dar um wget. A professora Nina falou de deixar esses arquivos no Vision, eh uma opcao. ii) Outra coisa que acho legal eh sempre separar em diretorios os arquivos, por exemplo, criar uma pasta "Data" para por os datasets, uma outra "Model" para deixar o modelo salvo e assim por diante.

O que acham?

abs

**Comment by mespadoto** [comment]
Opa, organização é fundamental!
Em minha defesa :-) não busquei fazer organização nenhuma, só subi os scripts rapidamente para quem quisesse ver e coloquei instruções básicas para executá-los, por isso até criei um repo separado, que pode ser descartado sem culpa.
Sou a favor de usar pull requests e da separação de dados e código. Prefiro a alternativa da rede Vision em vez do dropbox, só precisamos acertar os acessos para publicação (um sftp para upload e download via http já serviria).
Abraço.
Mateus
      De: Felsal <notifications@github.com>
 Para: MLIME/amazonproject <amazonproject@noreply.github.com> 
Cc: mespadoto <mespadoto@yahoo.com>; Mention <mention@noreply.github.com>
 Enviadas: Quinta-feira, 11 de Maio de 2017 12:07
 Assunto: [MLIME/amazonproject] Organizar repo (#1)
   
Oi pessoal, eu tenho algumas sugestoes:   
   - Acabei de criar uma branch ( - tf - nao sou bom com nomes). Acho que seria muito legal se concordássemos todos em não submeter commits diretos, mas sim usando pull requests para darmos a chance de todos opinarem... o que acham?
2 - @mespadoto ha duas coisas em como voce organizou o repositiorio que queria discutir. i) Sempre acho legal nao colocar arquivos que nao sao codigo no repositorio (tirando certas imagens pontuais, ou um pdf, mas bem pouco). Geralmente o que eu faco eu crio um script em bash para pegar os arquivos em algum lugar. Se voce olhar no meu branch tf eu fiz isso com o arquivo "train.csv". A questao que surge a seguir eh onde deixar esses arquivos. Como para baixar direto do kaggle precisa fazer um login, eu estava pensando em criar uma conta do grupo no dropbox para dar um wget. A professora Nina falou de deixar esses arquivos no Vision, eh uma opcao. ii) Outra coisa que acho legal eh sempre separar em diretorios os arquivos, por exemplo, criar uma pasta "Data" para por os datasets, uma outra "Model" para deixar o modelo salvo e assim por diante.O que acham?abs—
